dryrun_manager:
  restart: 'no'
  image: autoshift/autoshift-dryrun:master
  labels:
    io.rancher.scheduler.affinity:host_label: stack=dryrun,CLOUDPROVIDERSELECTOR
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: 'true'
    io.rancher.container.pull_image: always
  environment:
    APPOPTVARS: DRYRUNCONFIG
​
#  replace DRYRUNCONFIG with the real configuration: {"app_id": 57, "app_name":"acme-air","load_timespan":300,"desired_latency":200.0,"max_errrate":35.0,"budget_mon":200.0,"locations":[1],"db":{"mem_limit":2048000000,"cpu_quota":[200000],"scale":[1,3],"location":[1]},"loadbalancer": {"mem_limit":1024000000,"cpu_quota":[200000],"location":[1]},"webserver":{"mem_limit":1024000000,"cpu_quota":[200000],"scale":2,"location":[1]}}