get:
  responses:
    200:
      body:
        application/json:
          schema: <<resourcePathName>>
          example: |
            <<exampleItem>>
    404:
      body:
        application/json:
          # example: | # TODO: example
put:
  body:
    application/json:
      schema: <<resourcePathName>>
      example: |
        <<exampleItem>>
  responses:
    200:
      body:
        application/json:
          schema: <<resourcePathName>>
          example: |
            <<exampleItem>>
    404:
      body:
        application/json:
    400:
